create table BACKUPED_FILE_VERSION (
    ID VARCHAR PRIMARY KEY,
    BACKUPED_FILE_ID VARCHAR,
    BACKUP_TIME TIMESTAMP WITH TIME ZONE,
    CONSTRAINT VERSION_FILE_FK FOREIGN KEY (BACKUPED_FILE_ID) REFERENCES BACKUPED_FILE(ID)
);

create index version_file_ixf on BACKUPED_FILE_VERSION (BACKUPED_FILE_ID);

create table BACKUPED_FILE_VERSION_CONTENT (
    ID VARCHAR PRIMARY KEY,
    VERSION_ID VARCHAR,
    CONTENT BLOB,
    CONSTRAINT CONTENT_VERSION_FK FOREIGN KEY (VERSION_ID) REFERENCES BACKUPED_FILE_VERSION(ID)
);

create index content_version_ixf on BACKUPED_FILE_VERSION_CONTENT (VERSION_ID);