application.root.dir=file\\://${CLIENT_SERVER_BACKUP_ROOT_DIR}
%dev.application.root.dir=file\\://${HOME}/clientServerBackup/server
%test.application.root.dir=${HOME}/clientServerBackup-test/server
application.upload.dir=${application.root.dir}/uploads