application.root.dir=\${CLIENT_SERVER_BACKUP_ROOT_DIR}
%dev.application.root.dir=\${HOME}/clientServerBackup/server
%test.application.root.dir=$BUILD_DIR/target/test-data/server
application.upload.dir=\${application.root.dir}/uploads
quarkus.http.testport=0
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:\${application.root.dir}/database
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:
#%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:
quarkus.liquibase.migrate-at-start=true

